language: python
python:
#  - "2.6"
  - "2.7"
  # shutil.which
  #- "3.1" # Unsupported by Travis
  #- "3.2" # Does not support '{1} {0}'.format('one', 'two') >>> two one
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
    - sudo apt-get update
    # TODO: Move scipy/numpy to anaconda installation
    # https://gist.github.com/dan-blanchard/7045057
    - sudo apt-get build-dep python-scipy
    # gcc gfortran liblapack-dev libblas-dev libatlas-base-dev libatlas-dev
    - pip install pytest pytest-cov pytest-pep8
install:
    - pip install cython
    - pip install .
    - pip install -r requirements.txt
#script: python tests/test_utilities.py
script: py.test
branches:
  only:
    #- master
    - dev
